# Generated by Django 3.2.6 on 2021-09-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='web',
            field=models.URLField(blank=True),
        ),
    ]
