# Generated by Django 3.2.6 on 2021-09-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0005_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
