# Generated by Django 3.2.6 on 2021-09-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0006_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('web', models.URLField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, to='Back.Slug')),
            ],
        ),
    ]
