# Generated by Django 3.2.6 on 2021-09-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0007_work'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slug',
            new_name='Sluger',
        ),
    ]
