# Generated by Django 3.2.6 on 2021-09-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0008_rename_slug_sluger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sluger',
            old_name='slug',
            new_name='sluger',
        ),
    ]
