# Generated by Django 3.2.6 on 2021-09-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0010_auto_20210904_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workerner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('web', models.URLField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, to='Back.Valuer')),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
