# Generated by Django 3.2.6 on 2021-09-04 16:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0012_auto_20210904_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
