# Generated by Django 3.2.6 on 2021-09-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0019_auto_20210905_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/'),
        ),
    ]
