# Generated by Django 3.2.6 on 2021-09-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0022_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='timeperiod',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
