# Generated by Django 3.2.6 on 2021-09-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0023_work_timeperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
